version: '3.1'
services:
  firebase:
    environment:
      - FIREBASE_PROJECT_ID=fake
      - FIREBASE_TOKEN=fake
    image: voraciousdev/firebase-cli:1.0.1
    ports:
      - 32775:32775
      - 32776:32776
      - 32777:32777
      - 32778:32778
      - 35135:35135
    stdin_open: true
    tty: true
    volumes:
      - ./firebase:/firebase/volume
